SELECT 
    cols.TABLE_NAME,
    cols.COLUMN_NAME,
    cols.DATA_TYPE,
    cols.COLUMN_TYPE,
    cols.IS_NULLABLE,
    cols.COLUMN_DEFAULT,
    cols.EXTRA,
    tc.CONSTRAINT_TYPE,
    kcu.REFERENCED_TABLE_NAME,
    kcu.REFERENCED_COLUMN_NAME
FROM 
    INFORMATION_SCHEMA.COLUMNS cols
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu 
    ON cols.TABLE_SCHEMA = kcu.TABLE_SCHEMA
    AND cols.TABLE_NAME = kcu.TABLE_NAME
    AND cols.COLUMN_NAME = kcu.COLUMN_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc 
    ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
    AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA
    AND kcu.TABLE_NAME = tc.TABLE_NAME
WHERE 
    cols.TABLE_SCHEMA = 'nama_database'
ORDER BY 
    cols.TABLE_NAME, cols.ORDINAL_POSITION;
